<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function hello_menu_menu() {
  $items  = array();
  
  $items[ 'hello'] = array (
    'title' => 'Hello World from Jim Wu',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => array( 'access content'),
    'menu_name' => 'main-menu', 
    'weight' => 1,  
  );
  
  return $items;
}

function hello_menu_simple_hello () {
  //this function must return a string
  return t('Hello world!!');
}